### ISSUE TITLE
Formatting the generated files fails on Windows

### ISSUE THREAD

**Issue by eugenpodaru** [skyleague/therefore#166]
**Problem**

The latest release adds a step to format the generated files with biome. This is done by passing all the generated files as command line parameters to biome. For sufficiently large repos that command can easily be over the ([maximum command length on Windows ](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation)). As a result the command exits with an error

**Expectation**

Command completes successfully.

**Solution**

Either provide a way to skip the formatting or do the formatting in batches.

**Comment by pevisscher** [comment]
Fixed #178

**Comment by pevisscher** [comment]
@eugenpodaru was this one solved for you as well? I currently don't have a windows system to quickly verify for you

**Comment by eugenpodaru** [comment]
@pevisscher I did some testing and it's still complaining either that the command is too long, or that the syntax of the command is incorrect, so there might be some flag in biome itself. Based on some small tests it only starts working once the command is somewhere bellow 8000 chars.
