### ISSUE TITLE
Using ky as a client, still requires got as a devDependency when generating code

### ISSUE THREAD

**Issue by eugenpodaru** [skyleague/therefore#175]
**Description**

Since got is used in https://github.com/skyleague/therefore/blob/main/src/common/json/json.ts which is in turn used by the restclient builder, it is not possible to remove got as a (dev) dependency even when using ky as the http client.

**Expectation**

When using ky as a client, got should not be required as a dependency, or therefore should mark got as a dependency instead of as a devDependency

**Comment by pevisscher** [comment]
Fixed by #176

**Comment by eugenpodaru** [comment]
Great, thank you! Will test it as soon as it's released.

**Comment by eugenpodaru** [comment]
I tested, and it works as expected
